events {}

http {
    upstream api_servers {
        # Thuật toán Round Robin (Mặc định của Nginx)
        server node_1:8080;
        server node_2:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://api_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}